### PR TITLE
add method from removing info hash; fix #68

### LINKED ISSUE #68: No way to remove info hash from peer store
I am using the library in [a torrent client](https://github.com/cenkalti/rain). When a torrent is removed from the client, I would also like to remove the info hash from DHT node. Currently, there isn't any method for this. I can add one if you are okay with it. Would you like to see a PR?

### PR DESCRIPTION
**Pull request by cenkalti**

### CODE REVIEW

**Comment by cenkalti** [comment]
@nictuku Can you take a look please?

**Review by nictuku — APPROVED** [review]
Thanks!

**Comment by nictuku** [comment]
I'll look into why the CI failed

**Comment by cenkalti** [comment]
Hello @nictuku . Can this be merged?

**Comment by nictuku** [comment]
Sorry for the delay. Thank you!

**Pull request merged**
